# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on: [push, pull_request]
  # Run on PRs and pushes to the default branch.
  # push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]
  # # run every day at 23:15am
  # schedule:
  #   - cron:  '15 23 * * *'

jobs:

  # build on cpu hosts and upload to GHA
#   build_on_cpu:
#     runs-on: ${{ matrix.os }}
#     strategy:
#       matrix:
#         python-version: [3.8]
#         os: [ubuntu-18.04]
#     steps:
#     # Checkout the repository to the GitHub Actions runner
#     - name: Checkout
#       uses: actions/checkout@v2
#       with:
#         submodules: recursive
#     - name: create a dummy txt
#       run: |
#         < /dev/urandom tr -dc "[:alnum:]" | head -c1000 > test.txt
#     - name: Upload wheel as GHA artifact
#       uses: actions/upload-artifact@v2
#       with:
#         name: whatisthis.txt
#         path: test.txt
    

  # download from GHA, test on gpu and push to pypi
  test_on_gpu:
    runs-on: ubuntu-18.04
#     runs-on: linux.4xlarge.nvidia.gpu
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        # Optional, GitHub token, a Personal Access Token with `public_repo` scope if needed
        # Required, if artifact is from a different repo
        # Required, if repo is private a Personal Access Token with `repo` scope is needed
        github_token: ${{secrets.GITHUB_TOKEN}}
        # Required, workflow file name or ID
        workflow: 1758364806
        # Optional, the status or conclusion of a completed workflow to search for
        # Can be one of a workflow conclusion:
        #   "failure", "success", "neutral", "cancelled", "skipped", "timed_out", "action_required"
        # Or a workflow status:
        #   "completed", "in_progress", "queued"
        workflow_conclusion: failure
        branch: renfeichen-test-binary
        # Optional, will use specified workflow run
        run_id: 1758364806
        # Optional, uploaded artifact name,
        # will download all artifacts if not specified
        # and extract them in respective subdirectories
        # https://github.com/actions/download-artifact#download-all-artifacts
        name: torchrec_nightly.whl
    - name: Display structure of downloaded files
      run: ls -R
